### ISSUE TITLE
can not find " mdns.h"

### ISSUE THREAD

**Issue by TasLR** [AchimPieters/esp32-homekit-demo#14]
**Describe the bug**
when build  ws2811_led_strip project, occur "xx/homekit/src/port.c:159:10: fatal error:mdns.h: no file or directory

**Comment by AchimPieters** [comment]
@TasLR 

The error you're encountering, specifically regarding the missing mdns.h file, suggests that your project is trying to reference the mDNS (multicast DNS) library, but it is either not included or not properly configured in your build environment.

See  storage issue #6

**Comment by TasLR** [comment]
what kind of modifications do I need to make to get these examples to work

**Comment by TasLR** [comment]
what kind of modifications do I need to make to get these examples to work

**Comment by AchimPieters** [comment]
@TasLR  Normally you don't need to make a modification, let's start with a print screen of your error.

**Comment by KiLLuuuhh** [comment]
Hello, @AchimPieters!
First of all, thank you so much for the great work you’re doing—I’m really enjoying it! As @TasLR described, I am facing similar issues. I’m following this blog: https://www.studiopieters.nl/esp32-homekit-led/, and I am encountering the following issue:
`
[105/106] Generating binary image from built executable
esptool.py v4.7.0
Creating esp32 image...
Merged 2 ELF sections
Successfully created esp32 image.
Generated /project/examples/led/build/bootloader/bootloader.bin
[106/106] cd /project/examples/led/build/bootloader/esp-idf/esptool_py && /opt/esp/python_env/idf5.2_py3.10_env/bin/python /opt/esp/idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /project/examples/led/build/bootloader/bootloader.bin
Bootloader binary size 0x6860 bytes. 0x7a0 bytes (7%) free.
[717/865] Building C object esp-idf/wolfssl/CMakeFiles/__idf_wolfssl.dir/src/ssl_sess.c.obj
/project/components/wolfssl/src/ssl_sess.c:31:10: warning: #warning ssl_sess.c does not need to be compiled separately from ssl.c [-Wcpp]
   31 |         #warning ssl_sess.c does not need to be compiled separately from ssl.c
      |          ^~~~~~~
[718/865] Building C object esp-idf/wolfssl/CMakeFiles/__idf_wolfssl.dir/src/ssl_load.c.obj
/project/components/wolfssl/src/ssl_load.c:56:10: warning: #warning ssl_load.c does not need to be compiled separately from ssl.c [-Wcpp]
   56 |         #warning ssl_load.c does not need to be compiled separately from ssl.c
      |          ^~~~~~~
[719/865] Building C object esp-idf/wolfssl/CMakeFiles/__idf_wolfssl.dir/src/ssl_p7p12.c.obj
/project/components/wolfssl/src/ssl_p7p12.c:37:10: warning: #warning ssl_p7p12.c does not need to be compiled separately from ssl.c [-Wcpp]
   37 |         #warning ssl_p7p12.c does not need to be compiled separately from ssl.c
      |          ^~~~~~~
[829/865] Building C object esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj
FAILED: esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj
ccache /opt/esp/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/xtensa-esp32-elf-gcc -DESP_PLATFORM -DIDF_VER=\"v5.2.2\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -I/project/examples/led/build/config -I/project/components/homekit/include -I/project/components/homekit/src -I/opt/esp/idf/components/newlib/platform_include -I/opt/esp/idf/components/freertos/config/include -I/opt/esp/idf/components/freertos/config/include/freertos -I/opt/esp/idf/components/freertos/config/xtensa/include -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/include -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos -I/opt/esp/idf/components/freertos/esp_additions/include -I/opt/esp/idf/components/esp_hw_support/include -I/opt/esp/idf/components/esp_hw_support/include/soc -I/opt/esp/idf/components/esp_hw_support/include/soc/esp32 -I/opt/esp/idf/components/esp_hw_support/port/esp32/. -I/opt/esp/idf/components/heap/include -I/opt/esp/idf/components/log/include -I/opt/esp/idf/components/soc/include -I/opt/esp/idf/components/soc/esp32 -I/opt/esp/idf/components/soc/esp32/include -I/opt/esp/idf/components/hal/platform_port/include -I/opt/esp/idf/components/hal/esp32/include -I/opt/esp/idf/components/hal/include -I/opt/esp/idf/components/esp_rom/include -I/opt/esp/idf/components/esp_rom/include/esp32 -I/opt/esp/idf/components/esp_rom/esp32 -I/opt/esp/idf/components/esp_common/include -I/opt/esp/idf/components/esp_system/include -I/opt/esp/idf/components/esp_system/port/soc -I/opt/esp/idf/components/esp_system/port/include/private -I/opt/esp/idf/components/xtensa/esp32/include -I/opt/esp/idf/components/xtensa/include -I/opt/esp/idf/components/xtensa/deprecated_include -I/opt/esp/idf/components/lwip/include -I/opt/esp/idf/components/lwip/include/apps -I/opt/esp/idf/components/lwip/include/apps/sntp -I/opt/esp/idf/components/lwip/lwip/src/include -I/opt/esp/idf/components/lwip/port/include -I/opt/esp/idf/components/lwip/port/freertos/include -I/opt/esp/idf/components/lwip/port/esp32xx/include -I/opt/esp/idf/components/lwip/port/esp32xx/include/arch -I/opt/esp/idf/components/lwip/port/esp32xx/include/sys -I/project/components/wolfssl/include -I/project/components/wolfssl -I/project/components/wolfssl/wolfssl -I/project/components/wolfssl/wolfssl/wolfcrypt -I/project/components/wolfssl/wolfssl/wolfcrypt/port/Espressif -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/include/freertos -I/opt/esp/idf/components/esp_partition/include -I/opt/esp/idf/components/json/cJSON -I/opt/esp/idf/components/http_parser -I/opt/esp/idf/components/spi_flash/include -I/opt/esp/idf/components/nvs_flash/include -mlongcalls -Wno-frame-address  -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -DWOLFSSL_USER_SETTINGS -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Os -freorder-blocks -fmacro-prefix-map=/project/examples/led=. -fmacro-prefix-map=/opt/esp/idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -Wno-old-style-declaration -DHOMEKIT_MAX_CLIENTS=16 -DSPIFLASH_BASE_ADDR= -DESP_IDF -DHOMEKIT_DEBUG -MD -MT esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj -MF esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj.d -o esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj -c /project/components/homekit/src/port.c
/project/components/homekit/src/port.c:159:10: fatal error: mdns.h: No such file or directory
  159 | #include <mdns.h>
      |          ^~~~~~~~
compilation terminated.
[854/865] Building C object esp-idf/wolfssl/CMakeFiles/__idf_wolfssl.dir/src/internal.c.obj
ninja: build stopped: subcommand failed.
Missing "mdns.h" file name found in the following component(s): lwip(/opt/esp/idf/components/lwip/lwip/src/include/lwip/apps/mdns.h), openthread(/opt/esp/idf/components/openthread/openthread/src/core/config/mdns.h), openthread(/opt/esp/idf/components/openthread/openthread/include/openthread/mdns.h). Maybe one of the components needs to add the missing header directory to INCLUDE_DIRS of idf_component_register call in CMakeLists.txt.
ninja failed with exit code 1, output of the command is in the /project/examples/led/build/log/idf_py_stderr_output_550 and /project/examples/led/build/log/idf_py_stdout_output_550
root@145ae38d6530:/project/examples/led#
`

I am not doing any modification.

Thank you so much for your help!

**Comment by KiLLuuuhh** [comment]
> Hello, @AchimPieters! First of all, thank you so much for the great work you’re doing—I’m really enjoying it! As @TasLR described, I am facing similar issues. I’m following this blog: https://www.studiopieters.nl/esp32-homekit-led/, and I am encountering the following issue: `[105/106] Generating binary image from built executable esptool.py v4.7.0 Creating esp32 image... Merged 2 ELF sections Successfully created esp32 image. Generated /project/examples/led/build/bootloader/bootloader.bin [106/106] cd /project/examples/led/build/bootloader/esp-idf/esptool_py && /opt/esp/python_env/idf5.2_py3.10_env/bin/python /opt/esp/idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /project/examples/led/build/bootloader/bootloader.bin Bootloader binary size 0x6860 bytes. 0x7a0 bytes (7%) free. [717/865] Building C object esp-idf/wolfssl/CMakeFiles/__idf_wolfssl.dir/src/ssl_sess.c.obj /project/components/wolfssl/src/ssl_sess.c:31:10: warning: #warning ssl_sess.c does not need to be compiled separately from ssl.c [-Wcpp] 31 | #warning ssl_sess.c does not need to be compiled separately from ssl.c | ^~~~~~~ [718/865] Building C object esp-idf/wolfssl/CMakeFiles/__idf_wolfssl.dir/src/ssl_load.c.obj /project/components/wolfssl/src/ssl_load.c:56:10: warning: #warning ssl_load.c does not need to be compiled separately from ssl.c [-Wcpp] 56 | #warning ssl_load.c does not need to be compiled separately from ssl.c | ^~~~~~~ [719/865] Building C object esp-idf/wolfssl/CMakeFiles/__idf_wolfssl.dir/src/ssl_p7p12.c.obj /project/components/wolfssl/src/ssl_p7p12.c:37:10: warning: #warning ssl_p7p12.c does not need to be compiled separately from ssl.c [-Wcpp] 37 | #warning ssl_p7p12.c does not need to be compiled separately from ssl.c | ^~~~~~~ [829/865] Building C object esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj FAILED: esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj ccache /opt/esp/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/xtensa-esp32-elf-gcc -DESP_PLATFORM -DIDF_VER=\"v5.2.2\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -I/project/examples/led/build/config -I/project/components/homekit/include -I/project/components/homekit/src -I/opt/esp/idf/components/newlib/platform_include -I/opt/esp/idf/components/freertos/config/include -I/opt/esp/idf/components/freertos/config/include/freertos -I/opt/esp/idf/components/freertos/config/xtensa/include -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/include -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos -I/opt/esp/idf/components/freertos/esp_additions/include -I/opt/esp/idf/components/esp_hw_support/include -I/opt/esp/idf/components/esp_hw_support/include/soc -I/opt/esp/idf/components/esp_hw_support/include/soc/esp32 -I/opt/esp/idf/components/esp_hw_support/port/esp32/. -I/opt/esp/idf/components/heap/include -I/opt/esp/idf/components/log/include -I/opt/esp/idf/components/soc/include -I/opt/esp/idf/components/soc/esp32 -I/opt/esp/idf/components/soc/esp32/include -I/opt/esp/idf/components/hal/platform_port/include -I/opt/esp/idf/components/hal/esp32/include -I/opt/esp/idf/components/hal/include -I/opt/esp/idf/components/esp_rom/include -I/opt/esp/idf/components/esp_rom/include/esp32 -I/opt/esp/idf/components/esp_rom/esp32 -I/opt/esp/idf/components/esp_common/include -I/opt/esp/idf/components/esp_system/include -I/opt/esp/idf/components/esp_system/port/soc -I/opt/esp/idf/components/esp_system/port/include/private -I/opt/esp/idf/components/xtensa/esp32/include -I/opt/esp/idf/components/xtensa/include -I/opt/esp/idf/components/xtensa/deprecated_include -I/opt/esp/idf/components/lwip/include -I/opt/esp/idf/components/lwip/include/apps -I/opt/esp/idf/components/lwip/include/apps/sntp -I/opt/esp/idf/components/lwip/lwip/src/include -I/opt/esp/idf/components/lwip/port/include -I/opt/esp/idf/components/lwip/port/freertos/include -I/opt/esp/idf/components/lwip/port/esp32xx/include -I/opt/esp/idf/components/lwip/port/esp32xx/include/arch -I/opt/esp/idf/components/lwip/port/esp32xx/include/sys -I/project/components/wolfssl/include -I/project/components/wolfssl -I/project/components/wolfssl/wolfssl -I/project/components/wolfssl/wolfssl/wolfcrypt -I/project/components/wolfssl/wolfssl/wolfcrypt/port/Espressif -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/include/freertos -I/opt/esp/idf/components/esp_partition/include -I/opt/esp/idf/components/json/cJSON -I/opt/esp/idf/components/http_parser -I/opt/esp/idf/components/spi_flash/include -I/opt/esp/idf/components/nvs_flash/include -mlongcalls -Wno-frame-address -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -DWOLFSSL_USER_SETTINGS -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Os -freorder-blocks -fmacro-prefix-map=/project/examples/led=. -fmacro-prefix-map=/opt/esp/idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -Wno-old-style-declaration -DHOMEKIT_MAX_CLIENTS=16 -DSPIFLASH_BASE_ADDR= -DESP_IDF -DHOMEKIT_DEBUG -MD -MT esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj -MF esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj.d -o esp-idf/homekit/CMakeFiles/__idf_homekit.dir/src/port.c.obj -c /project/components/homekit/src/port.c /project/components/homekit/src/port.c:159:10: fatal error: mdns.h: No such file or directory 159 | #include <mdns.h> | ^~~~~~~~ compilation terminated. [854/865] Building C object esp-idf/wolfssl/CMakeFiles/__idf_wolfssl.dir/src/internal.c.obj ninja: build stopped: subcommand failed. Missing "mdns.h" file name found in the following component(s): lwip(/opt/esp/idf/components/lwip/lwip/src/include/lwip/apps/mdns.h), openthread(/opt/esp/idf/components/openthread/openthread/src/core/config/mdns.h), openthread(/opt/esp/idf/components/openthread/openthread/include/openthread/mdns.h). Maybe one of the components needs to add the missing header directory to INCLUDE_DIRS of idf_component_register call in CMakeLists.txt. ninja failed with exit code 1, output of the command is in the /project/examples/led/build/log/idf_py_stderr_output_550 and /project/examples/led/build/log/idf_py_stdout_output_550 root@145ae38d6530:/project/examples/led#`
> 
> I am not doing any modification.
> 
> Thank you so much for your help!

I made two changes which made the build work:
1.` idf.py add-dependency espressif/mdn`
2. added `espressif__mdns` as a PRIV_REQUIRES to `components\homekit\CMakeLists.txt`.

Unfortunately, I cannot validate this changes since I am not familiar with the setup.

**Comment by AchimPieters** [comment]
@KiLLuuuhh It appears that the cause of the 'issue' may have been identified. You can try running the following command: `docker run -it -v ~/esp32-homekit-demo:/project -w /project espressif/idf:release-v5.3` instead of `docker run -it -v ~/esp32-homekit-demo:/project -w /project espressif/idf:release-v5.2.2` Due to the continuous development of the repository and the use of the latest updates, this may be the cause of the issue. Please let me know if this resolves the problem.

**Comment by KiLLuuuhh** [comment]
@AchimPieters Thanks for your reply. Yes this resolves the problem.
