### ISSUE TITLE
Bad submodule commits?

### ISSUE THREAD

**Issue by gojimmypi** [AchimPieters/esp32-homekit-demo#15]
Related to https://github.com/wolfSSL/wolfssl/issues/8266:

I encountered an error when attempting to update submodules:

![image](https://github.com/user-attachments/assets/bd5d9d7e-2ea0-4515-bc20-4175c79e745a)

From [https://github.com/AchimPieters/esp32-homekit-demo/tree/main/components](https://github.com/AchimPieters/esp32-homekit-demo/tree/main/components):

* [esp32-button @ 4ba1c79](https://github.com/AchimPieters/esp32-button/tree/4ba1c79ad8b8da7c4a5f686f015b7445102516e7) - 404
* [esp32-library @ 47fabc5](https://github.com/UncleRus/esp-idf-lib/tree/47fabc5c770c460e9347969e7ade38d473a4355f) - ok
* [homekit @ 338fbdf](https://github.com/AchimPieters/esp32-homekit/tree/338fbdf4ab749031182871032a4c044b5ad1ed42) - 404
* [ws2811 @ 41a4e6a](https://github.com/AchimPieters/esp32-ws2811/tree/41a4e6a52f4d70e4034f632c2443e42ced3dd4d1)  - ok

From commandline:

```
$ git submodule update --init --recursive --remote
gojimmypi:/mnt/c/workspace/esp32-homekit-demo-gojimmypi-pr/examples/led
$ git submodule update
fatal: remote error: upload-pack: not our ref 4ba1c79ad8b8da7c4a5f686f015b7445102516e7
fatal: Fetched in submodule path '../../components/esp32-button', but it did not contain 4ba1c79ad8b8da7c4a5f686f015b7445102516e7. Direct fetching of that commit failed.
fatal:
```

**Comment by AchimPieters** [comment]
@gojimmypi Thank you for bringing this to my attention! The issue was caused by a file corruption during the upload process. I’ve identified and resolved the problem, and everything should now be working as expected.

**Comment by gojimmypi** [comment]
Awesome, thanks for your prompt attention! Submodule corruption issue confirmed resolved.
